# Generated by Django 3.2.7 on 2021-10-18 19:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_auto_20211018_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAMLResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('authn_response', models.TextField()),
                ('identity', models.TextField()),
                ('user_name', models.TextField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sso.samlconnection')),
            ],
        ),
    ]
