name: Test

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+
    branches: master

jobs:
  test-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.10]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        working-directory: ./ossso_app
        run: |
          poetry install
          sudo apt-get install xmlsec1
      - name: Test
        env:
          DJANGO_SECRET_KEY: abc-456
          SSO_BASE_URL: localhost
        working-directory: ./ossso_app
        run: |
          poetry run python manage.py test


  deploy:
    runs-on: ubuntu-latest
    needs: [test-api]
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST_KEY }}
      - name: Push to Dokku Dev
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          ssh dokku@cloud.stuartquin.com -t "dokku config:set --no-restart ossso-dev GIT_BRANCH=${GITHUB_REF}"
          git remote add dokku dokku@cloud.stuartquin.com:ossso-dev
          git push -f dokku ${GITHUB_SHA}:master
      - name: Push to Dokku Prod
        if: startsWith( github.ref, 'refs/tags/v')
        run: |
          ssh dokku@cloud.stuartquin.com -t "dokku config:set --no-restart ossso GIT_BRANCH=${GITHUB_REF}"
          git remote add dokku dokku@cloud.stuartquin.com:ossso
          git push -f dokku ${GITHUB_SHA}:master
